# Generated by Django 5.1.7 on 2025-07-10 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_alter_institutiondocument_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldresponse',
            name='value_option',
        ),
        migrations.RemoveField(
            model_name='fieldresponse',
            name='value_multi',
        ),
        migrations.RemoveField(
            model_name='fieldresponse',
            name='field',
        ),
        migrations.RemoveField(
            model_name='fieldresponse',
            name='response',
        ),
        migrations.RemoveField(
            model_name='productfield',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productresponse',
            name='product',
        ),
        migrations.DeleteModel(
            name='FieldOption',
        ),
        migrations.DeleteModel(
            name='FieldResponse',
        ),
        migrations.DeleteModel(
            name='ProductField',
        ),
        migrations.DeleteModel(
            name='ProductResponse',
        ),
    ]
