# Generated by Django 5.1.7 on 2025-07-10 09:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0007_clientcompanyproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallGroup',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_call_groups', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_groups', to='institution.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('verified', 'Verified'), ('called', 'Called'), ('achieved', 'Achieved'), ('flagged', 'Flagged')], default='new', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='institution.product')),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback', models.JSONField(blank=True, help_text="JSON object containing feedback responses based on product's feedback_fields", null=True)),
                ('status', models.CharField(choices=[('failed', 'Failed'), ('completed', 'Completed'), ('busy', 'Busy')], default='completed', max_length=20)),
                ('made_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('made_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calls_made', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calls', to='call.contact')),
            ],
        ),
        migrations.CreateModel(
            name='CallGroupUser',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('call_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='call.callgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_group_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('call_group', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CallGroupContact',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('attended_to', 'Attended to'), ('not_attended', 'Not attended'), ('follow_up', 'Follow up')], default='new', max_length=20)),
                ('call_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='call.callgroup')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_groups', to='call.contact')),
            ],
            options={
                'unique_together': {('call_group', 'contact')},
            },
        ),
    ]
