# Generated by Django 5.1.7 on 2025-07-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('verified', 'Verified'), ('called', 'Called'), ('archieved', 'Archieved'), ('flagged', 'Flagged')], default='new', max_length=20),
        ),
    ]
