# Generated by Django 5.1.7 on 2025-07-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0002_alter_contact_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('verified', 'Verified'), ('called', 'Called'), ('archived', 'Archived'), ('flagged', 'Flagged')], default='new', max_length=20),
        ),
    ]
