# Generated by Django 5.1.7 on 2025-07-24 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0003_alter_contact_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='remarks',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='callgroupcontact',
            name='status',
            field=models.CharField(choices=[('attended_to', 'Attended to'), ('not_attended', 'Not attended'), ('follow_up', 'Follow up'), ('new', 'New'), ('exported', 'Exported'), ('asigned', 'Assigned'), ('ready_to_export', 'Ready to export')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('attended_to', 'Attended To'), ('archived', 'Archived'), ('flagged', 'Flagged'), ('ready_to_export', 'Ready To Export'), ('exported', 'Exported')], default='new', max_length=20),
        ),
    ]
