# Generated by Django 5.1.7 on 2025-07-24 07:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0004_contact_remarks_alter_callgroupcontact_status_and_more'),
        ('institution', '0008_alter_clientcompany_api_key'),
        ('users', '0002_rename_institution_role_institution_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='product',
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('device_id', models.CharField(max_length=225)),
                ('extension', models.CharField(max_length=225)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CallGroupAgent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_group_agents', to='call.agent')),
                ('call_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='call.callgroup')),
            ],
            options={
                'unique_together': {('call_group', 'agent')},
            },
        ),
        migrations.CreateModel(
            name='ContactProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_products', to='call.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_contact_products', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_products', to='institution.product')),
            ],
            options={
                'unique_together': {('contact', 'product')},
            },
        ),
        migrations.AlterField(
            model_name='callgroupcontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_groups', to='call.contactproduct'),
        ),
        migrations.DeleteModel(
            name='CallGroupUser',
        ),
    ]
