# Generated by Django 5.1.7 on 2025-07-24 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0005_remove_contact_product_agent_callgroupagent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='made_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calls_made', to='call.callgroupagent'),
        ),
    ]
