# Generated by Django 5.1.7 on 2025-07-24 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0006_alter_call_made_by'),
        ('institution', '0008_alter_clientcompany_api_key'),
        ('users', '0002_rename_institution_role_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='institution.institution'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactproduct',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_contact_products', to='users.profile'),
        ),
    ]
