# Generated by Django 5.1.7 on 2025-07-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0007_contact_institution_alter_contactproduct_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
