# Generated by Django 5.1.7 on 2025-07-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0008_alter_contact_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
