# Generated by Django 5.1.7 on 2025-07-25 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0009_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calls', to='call.contactproduct'),
        ),
    ]
